version: '3'
services:
  db:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT}:5432"
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "./main"]
    image: generalledger/api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    links:
      - db
